export const QUESTION = 'QUESTION';
export const QUESTION_FULFILLED = 'QUESTION_FULFILLED';
export const QUESTION_REJECTED = 'QUESTION_REJECTED';

export const QUESTIONS = 'QUESTIONS';
export const QUESTIONS_FULFILLED = 'QUESTIONS_FULFILLED';
export const QUESTIONS_REJECTED = 'QUESTIONS_REJECTED';

export const USER = 'USER';
export const USER_FULFILLED = 'USER_FULFILLED';
export const USER_REJECTED = 'USER_REJECTED';

export const URI = 'URI';
export const URI_FULFILLED = 'URI_FULFILLED';
export const URI_REJECTED = 'URI_REJECTED';

export const ANSWER = 'ANSWER';
export const ANSWER_FULFILLED = 'ANSWER_FULFILLED';
export const ANSWER_REJECTED = 'ANSWER_REJECTED';
